# Generated by Django 4.0.4 on 2022-06-12 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='orders/images/default-food.png', upload_to='orders/images/food/')),
                ('description', models.TextField()),
                ('max_topping', models.IntegerField(default=0)),
                ('price_type', models.CharField(choices=[('small & large', 'Small & Large'), ('small', 'Small'), ('large', 'Large'), ('normal', 'Normal')], default='', max_length=50)),
                ('base_price', models.CharField(default='0', max_length=50)),
                ('type_food', models.CharField(choices=[('salad', 'Salad'), ('subs', 'Subs'), ('dinner', 'Dinner'), ('pizza', 'Pizza'), ('pasta', 'Pasta')], default='breakfast', max_length=64)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Popular_Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.food')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('delivered', 'Delivered')], default='pending', max_length=64)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.food')),
                ('toppings', models.ManyToManyField(to='orders.toppings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food_Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('toppings', models.ManyToManyField(to='orders.toppings')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='list_toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.food_toppings'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.food')),
                ('toppings', models.ManyToManyField(to='orders.toppings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
